### ISSUE TITLE
django-session-header to pypi

### ISSUE THREAD

**Issue by rttomlinson** [ryanhiebert/django-session-header#3]
Hey,

I got the library working locally and working on deploying my application. If you're okay with it, it would be nice to have on pypi so I don't need to do an extra step for installation in the Dockerfile. I haven't flushed out csrf yet but that's the next step. Thanks!

**Comment by ryanhiebert** [comment]
Sweet. I'll try to do that tomorrow!

**Comment by ryanhiebert** [comment]
I wasn't able to get to it today, but I have not forgotten.

**Comment by rttomlinson** [comment]
No worries!

**Comment by rttomlinson** [comment]
Hey, just wanted to follow up on uploading to PyPI. I think I ran into an issue with the library overwriting the Access-Control-Expose-Headers if I try to set any in my views. Not sure if this is intentional but want to check. Going to go ahead and make a fork and try to fix it.

**Comment by rttomlinson** [comment]
Nvm, the expose headers is all on me. I'm setting it in Django configs but want to modify it on my response.

**Comment by ryanhiebert** [comment]
Sorry for the delay, it's just been hectic at work. I'll make sure to give it an hour this morning. I've been stalling because I want to switch it to using poetry, and change the name of the package to import to `django_session_header` to match the PyPI package name.

**Comment by ryanhiebert** [comment]
What version of Python and Django are you on? I want to make sure my release supports your current use-case, but otherwise I'm inclined to default to making the version compatibility restrictive.

**Comment by rttomlinson** [comment]
Hey Ryan,

I'm using Python 3.7 and Django 2.1.7. Thanks so much for doing this.

**Comment by ryanhiebert** [comment]
Sweet. I'm still stuck on 3.6 because of libraries we still need that are messed up with 3.7's `async` keyword, but I'm glad that at least this first release will be fine to just be 3.6+.

**Comment by ryanhiebert** [comment]
OK, it's finally shipped. Note that the path to import has changed from `session_header` to `django_session_header`, primarily because of strong opinions that Poetry has about package names.

**Comment by rttomlinson** [comment]
Sounds good. I'll check this out and let you know how pulling it from pypi goes.

**Comment by rttomlinson** [comment]
Can you explain what you mean by you're stuck on 3.6? Do you mean that you need to use 3.6 in relation to this library or is this another project/work where you're using 3.6 and you have dependencies that don't like 3.7's `async`?

**Comment by ryanhiebert** [comment]
Another work. The project I can't up with this I've got, but never used it on. This one is fine with 3.7
